version: "3.9"

services:
  back:
    container_name: node_api_motors
    build:
      context: ./motors-shop-BackEnd/
    ports:
      - 3001:3001
    env_file:
      - ./env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate dev && npm run start:dev"
    volumes:
      - ./back/:/app 
  
  db:
    container_name: db_motors
    image: postgres:15
    ports:
      - 5431:5432
    env_file:
      - ./env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s