version: "3.9"

services:
  back:
    container_name: motors_shop__server
    build:
      context: .
    ports:
      - ${SERVER_PORT:-3001}:${SERVER_PORT:-3001}
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    command: sh -c "npx prisma migrate dev && npm run start:dev"
    volumes:
      - .:/app 
  
  database:
    container_name: motors_shop__database
    image: postgres:15-alpine
    ports:
      - ${LOCAL_PG_PORT:-5454}:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s